#!/bin/bash
set -ev

echo "Setting up the Google Cloud SDK"
gcloud version || true
# Download and install GCloud if it does not exist in cache
if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
  echo "Google Cloud not cached - downloading and installing"
  rm -rf "$HOME"/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash &> /dev/null;
fi
gcloud version
echo "Done setting up the Google Cloud SDK"