#!/bin/bash

# Build the Next.js application
npm run build

# Build the Docker Image
docker build -f travis.Dockerfile -t $PROJECT_NAME .

# Authenticate with GCloud SDK
gcloud auth activate-service-account --key-file keyfile.json
gcloud auth configure-docker
gcloud config set project $PROJECT_NAME

# Login to Google Container Registry using encrypted Keyfile
# cat keyfile.json | docker login -u _json_key --password-stdin https://$REGISTRY_HOST_NAME

# Push the image to Google Container Registry
docker tag $PROJECT_NAME $REGISTRY_HOST_NAME/$PROJECT_NAME/$PROJECT_NAME:latest
docker push $REGISTRY_HOST_NAME/$PROJECT_NAME/$PROJECT_NAME:latest
