#!/bin/bash
set -e

# Used to check if the image tag already exists in the repository
TAG_EXISTS="$(gcloud container images list-tags --format='get(tags)' "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$PROJECT_NAME" | grep "$PROJECT_VERSION")"

# Build, tag and push to registry if the tag ($PROJECT_VERSION) does not exist in repository
if [ -z "$TAG_EXISTS" ]; then
  echo "Building and pushing the Docker Image with tag $PROJECT_VERSION to the repository"

  # Build the Docker Image
  docker build -f travis.Dockerfile -t "$PROJECT_NAME" .

  # Tag and push image as 'latest' to GCR
  docker tag "$PROJECT_NAME" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$PROJECT_NAME":latest
  docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$PROJECT_NAME":latest

  # Tag and push image as '$PROJECT_VERSION' to GCR
  docker tag "$PROJECT_NAME" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$PROJECT_NAME":"$PROJECT_VERSION"
  docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$PROJECT_NAME":"$PROJECT_VERSION"
else
  echo "Image with tag $PROJECT_VERSION already exists in the repository."
fi

terraform init $TF_INIT_CLI_OPTIONS
terraform apply $TF_APPLY_CLI_OPTIONS
